services:
  database:
    image: postgres:17.6-alpine
    container_name: payment-api-database
    restart: always
    env_file:
      - ./docker_compose_env/database.env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
